### ISSUE TITLE
Issue with certificate authentication

### ISSUE THREAD

**Issue by ZNKitanovic** [jeswils-ap/anaplan-api#39]
In line 64 
https://github.com/jeswils-ap/anaplan-api/blob/main/anaplan_api/anaplan/authentication/CertificateAuthentication.py

The self.certificate_details.header is already encoded. The re-encoding makes it not match the CA Signed certificate stored within Anaplan. 
The line should just be:
self.certificate_details.header

**Comment by jeswils-ap** [comment]
Thanks for bringing this to my attention.

Fixed in https://github.com/jeswils-ap/anaplan-api/pull/40

**Comment by ZNKitanovic** [comment]
Thanks for the quick turnaround!
